#!/usr/bin/env python3
"""Seed the exercise_catalog table with 80 exercises.

Run from backend/api directory:
    python -m scripts.seed_exercises
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db.session import SessionLocal
from app.repositories.exercise_repository import ExerciseRepository

EXERCISES: list[dict] = [
    # ── PECHO (Chest) ─────────────────────────────────────────────────────────
    {
        "name": "Bench Press",
        "name_es": "Press Banca Plano",
        "description_es": "Ejercicio compuesto para el desarrollo del pecho",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor",
        "secondary_muscles": '["Tríceps", "Deltoides anterior"]',
        "equipment_required": '["Barra", "Banco"]',
        "equipment_alternatives": '["Mancuernas", "Máquina de press"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Recuéstate en el banco con los pies apoyados en el suelo", "Agarra la barra con agarre ligeramente más ancho que los hombros", "Baja la barra hasta el pecho de forma controlada", "Empuja hasta extender completamente los brazos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Incline Bench Press",
        "name_es": "Press Banca Inclinado",
        "description_es": "Variante inclinada del press de banca para enfatizar la parte superior del pecho",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor (porción clavicular)",
        "secondary_muscles": '["Tríceps", "Deltoides anterior"]',
        "equipment_required": '["Barra", "Banco inclinado"]',
        "equipment_alternatives": '["Mancuernas", "Máquina de press inclinado"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Ajusta el banco a 30-45 grados", "Agarra la barra con agarre más ancho que los hombros", "Baja la barra hacia la parte superior del pecho", "Empuja hasta extender los brazos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Dumbbell Flyes",
        "name_es": "Aperturas con Mancuernas",
        "description_es": "Ejercicio de aislamiento para el pecho usando mancuernas",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor",
        "secondary_muscles": '["Deltoides anterior"]',
        "equipment_required": '["Mancuernas", "Banco"]',
        "equipment_alternatives": '["Poleas", "Máquina de aperturas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Recuéstate en el banco con una mancuerna en cada mano", "Extiende los brazos sobre el pecho con codos ligeramente flexionados", "Abre los brazos hacia los lados de forma controlada", "Regresa a la posición inicial contrayendo el pecho"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Dips",
        "name_es": "Fondos en Paralelas",
        "description_es": "Ejercicio de peso corporal para el pecho y tríceps",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor",
        "secondary_muscles": '["Tríceps", "Deltoides anterior"]',
        "equipment_required": '["Barras paralelas"]',
        "equipment_alternatives": '["Banco"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Sujétate en las barras paralelas con los brazos extendidos", "Inclínate ligeramente hacia adelante", "Baja el cuerpo flexionando los codos hasta 90 grados", "Empuja hacia arriba hasta extender los brazos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Chest Press Machine",
        "name_es": "Press Pecho Máquina",
        "description_es": "Versión en máquina del press de pecho, ideal para principiantes",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor",
        "secondary_muscles": '["Tríceps"]',
        "equipment_required": '["Máquina de press de pecho"]',
        "equipment_alternatives": '["Mancuernas", "Barra"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Ajusta el asiento para que los mangos queden a la altura del pecho", "Empuja los mangos hacia adelante hasta extender los brazos", "Regresa de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Cable Crossover",
        "name_es": "Crossover en Polea",
        "description_es": "Ejercicio en polea para definir y aislar el pecho",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor",
        "secondary_muscles": '["Deltoides anterior"]',
        "equipment_required": '["Poleas dobles"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Colócate en el centro entre las poleas altas", "Agarra un cable en cada mano", "Une las manos al frente cruzando ligeramente", "Regresa a la posición inicial de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Push-ups",
        "name_es": "Flexiones",
        "description_es": "Ejercicio de peso corporal clásico para el pecho",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor",
        "secondary_muscles": '["Tríceps", "Deltoides anterior", "Core"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 40,
        "instructions_es": '["Colócate en posición de plancha con manos a la anchura de hombros", "Baja el pecho hacia el suelo flexionando los codos", "Empuja hacia arriba hasta extender los brazos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── ESPALDA (Back) ────────────────────────────────────────────────────────
    {
        "name": "Pull-ups",
        "name_es": "Dominadas",
        "description_es": "Ejercicio de peso corporal fundamental para la espalda",
        "muscle_group": "Espalda",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Bíceps", "Romboides", "Trapecio inferior"]',
        "equipment_required": '["Barra de dominadas"]',
        "equipment_alternatives": '["Máquina de jalón"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Cuelga de la barra con agarre supino o prono", "Jala el cuerpo hacia arriba hasta que el mentón supere la barra", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Barbell Row",
        "name_es": "Remo con Barra",
        "description_es": "Ejercicio compuesto para el desarrollo de la espalda media",
        "muscle_group": "Espalda",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Romboides", "Trapecio", "Bíceps"]',
        "equipment_required": '["Barra"]',
        "equipment_alternatives": '["Mancuernas", "Máquina de remo"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Inclínate hacia adelante con la espalda recta", "Agarra la barra con agarre prono", "Jala la barra hacia el abdomen", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Dumbbell Row",
        "name_es": "Remo con Mancuerna",
        "description_es": "Remo unilateral con mancuerna para la espalda",
        "muscle_group": "Espalda",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Romboides", "Bíceps"]',
        "equipment_required": '["Mancuerna", "Banco"]',
        "equipment_alternatives": '["Polea baja"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Apoya una rodilla y mano en el banco", "Agarra la mancuerna con la mano libre", "Jala la mancuerna hacia la cadera", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Lat Pulldown",
        "name_es": "Jalón al Pecho",
        "description_es": "Ejercicio en máquina de polea para el dorsal ancho",
        "muscle_group": "Espalda",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Bíceps", "Romboides"]',
        "equipment_required": '["Máquina de jalón"]',
        "equipment_alternatives": '["Bandas elásticas", "Barra de dominadas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Siéntate frente a la máquina y sujeta la barra", "Jala la barra hacia el pecho manteniendo la espalda recta", "Regresa a la posición inicial de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Seated Cable Row",
        "name_es": "Remo en Máquina",
        "description_es": "Remo sentado en polea para la espalda media",
        "muscle_group": "Espalda",
        "primary_muscle": "Romboides",
        "secondary_muscles": '["Dorsal ancho", "Trapecio medio", "Bíceps"]',
        "equipment_required": '["Polea baja"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Siéntate frente a la polea con los pies apoyados", "Agarra el mango y jala hacia el abdomen", "Aprieta los omóplatos al final del movimiento", "Regresa de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Deadlift",
        "name_es": "Peso Muerto",
        "description_es": "Ejercicio compuesto fundamental para toda la cadena posterior",
        "muscle_group": "Espalda",
        "primary_muscle": "Erector espinal",
        "secondary_muscles": '["Glúteos", "Isquiotibiales", "Trapecio", "Dorsal ancho"]',
        "equipment_required": '["Barra"]',
        "equipment_alternatives": '["Mancuernas", "Kettlebell"]',
        "difficulty": "advanced",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 75,
        "instructions_es": '["Colócate de pie con los pies a la anchura de caderas", "Dobla las rodillas y agarra la barra con agarre prono o mixto", "Mantén la espalda recta y el pecho hacia arriba", "Extiende caderas y rodillas hasta quedar de pie", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Face Pulls",
        "name_es": "Face Pulls",
        "description_es": "Ejercicio con polea para los deltoides posteriores y manguito rotador",
        "muscle_group": "Espalda",
        "primary_muscle": "Deltoides posterior",
        "secondary_muscles": '["Trapecio", "Manguito rotador"]',
        "equipment_required": '["Polea alta", "Cuerda"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Ajusta la polea a la altura de la cara", "Jala la cuerda hacia la cara separando las manos", "Aprieta los omóplatos al final", "Regresa de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── PIERNAS (Legs) ────────────────────────────────────────────────────────
    {
        "name": "Barbell Squat",
        "name_es": "Sentadilla Libre",
        "description_es": "El rey de los ejercicios de piernas",
        "muscle_group": "Piernas",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Isquiotibiales", "Core"]',
        "equipment_required": '["Barra", "Rack de sentadillas"]',
        "equipment_alternatives": '["Mancuernas", "Peso corporal"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 75,
        "instructions_es": '["Coloca la barra sobre los trapecios", "Pies a la anchura de hombros, puntas ligeramente abiertas", "Baja flexionando caderas y rodillas hasta 90 grados", "Sube empujando desde los talones"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Leg Press",
        "name_es": "Prensa de Pierna",
        "description_es": "Máquina de piernas para cuádriceps y glúteos",
        "muscle_group": "Piernas",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Isquiotibiales"]',
        "equipment_required": '["Prensa de pierna"]',
        "equipment_alternatives": '["Sentadilla con mancuernas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Siéntate en la máquina con los pies en la plataforma", "Baja la plataforma flexionando las rodillas a 90 grados", "Empuja hasta casi extender las piernas"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Leg Extension",
        "name_es": "Extensión de Cuádriceps",
        "description_es": "Ejercicio de aislamiento para los cuádriceps",
        "muscle_group": "Piernas",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '[]',
        "equipment_required": '["Máquina de extensión de pierna"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Siéntate en la máquina con los tobillos bajo el rodillo", "Extiende las piernas hasta quedar rectas", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Leg Curl",
        "name_es": "Curl de Isquiotibiales",
        "description_es": "Ejercicio de aislamiento para los isquiotibiales",
        "muscle_group": "Piernas",
        "primary_muscle": "Isquiotibiales",
        "secondary_muscles": '["Glúteos"]',
        "equipment_required": '["Máquina de curl de pierna"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Recuéstate boca abajo en la máquina", "Flexiona las rodillas llevando los talones hacia los glúteos", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Lunges",
        "name_es": "Zancadas",
        "description_es": "Ejercicio unilateral para piernas y glúteos",
        "muscle_group": "Piernas",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Isquiotibiales"]',
        "equipment_required": '[]',
        "equipment_alternatives": '["Mancuernas", "Barra"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Da un paso largo hacia adelante", "Baja la rodilla trasera hacia el suelo", "Regresa a la posición inicial", "Alterna piernas"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Hip Thrust",
        "name_es": "Hip Thrust",
        "description_es": "Ejercicio principal para el desarrollo de glúteos",
        "muscle_group": "Piernas",
        "primary_muscle": "Glúteo mayor",
        "secondary_muscles": '["Isquiotibiales", "Core"]',
        "equipment_required": '["Banco", "Barra"]',
        "equipment_alternatives": '["Mancuernas", "Bandas elásticas"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Apoya los omóplatos en el banco", "Coloca la barra sobre las caderas", "Empuja las caderas hacia arriba contrayendo glúteos", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Calf Raise",
        "name_es": "Elevación de Gemelos",
        "description_es": "Ejercicio de aislamiento para los gemelos",
        "muscle_group": "Piernas",
        "primary_muscle": "Gastrocnemio",
        "secondary_muscles": '["Sóleo"]',
        "equipment_required": '[]',
        "equipment_alternatives": '["Máquina de gemelos", "Mancuernas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 40,
        "instructions_es": '["Párate con los pies a la anchura de caderas", "Elévate en las puntas de los pies lo máximo posible", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Goblet Squat",
        "name_es": "Sentadilla Goblet",
        "description_es": "Sentadilla frontal sosteniendo una mancuerna o kettlebell",
        "muscle_group": "Piernas",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Core"]',
        "equipment_required": '["Mancuerna"]',
        "equipment_alternatives": '["Kettlebell", "Peso corporal"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 55,
        "instructions_es": '["Sostén la mancuerna con ambas manos frente al pecho", "Pies a la anchura de hombros", "Baja en sentadilla hasta 90 grados", "Sube empujando desde los talones"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── HOMBROS (Shoulders) ───────────────────────────────────────────────────
    {
        "name": "Military Press",
        "name_es": "Press Militar",
        "description_es": "Ejercicio compuesto principal para los hombros",
        "muscle_group": "Hombros",
        "primary_muscle": "Deltoides",
        "secondary_muscles": '["Tríceps", "Trapecio"]',
        "equipment_required": '["Barra"]',
        "equipment_alternatives": '["Mancuernas", "Máquina de hombros"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["De pie o sentado, agarra la barra a la altura de los hombros", "Empuja hacia arriba hasta extender los brazos", "Baja de forma controlada a la posición inicial"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Lateral Raises",
        "name_es": "Elevaciones Laterales",
        "description_es": "Ejercicio de aislamiento para el deltoides lateral",
        "muscle_group": "Hombros",
        "primary_muscle": "Deltoides lateral",
        "secondary_muscles": '["Trapecio"]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '["Poleas", "Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie con una mancuerna en cada mano", "Eleva los brazos lateralmente hasta la altura de los hombros", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Front Raises",
        "name_es": "Elevaciones Frontales",
        "description_es": "Ejercicio de aislamiento para el deltoides anterior",
        "muscle_group": "Hombros",
        "primary_muscle": "Deltoides anterior",
        "secondary_muscles": '["Pectoral mayor (porción clavicular)"]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '["Barra", "Poleas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie con una mancuerna en cada mano frente a los muslos", "Eleva los brazos hacia adelante hasta la altura de los hombros", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Rear Delt Flyes",
        "name_es": "Pájaros",
        "description_es": "Ejercicio para el deltoides posterior",
        "muscle_group": "Hombros",
        "primary_muscle": "Deltoides posterior",
        "secondary_muscles": '["Romboides", "Trapecio medio"]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '["Poleas", "Máquina de pájaros"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Inclínate hacia adelante con espalda recta", "Con mancuernas colgando, abre los brazos hacia los lados", "Aprieta el deltoides posterior al final", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Arnold Press",
        "name_es": "Arnold Press",
        "description_es": "Variante del press de hombros con rotación",
        "muscle_group": "Hombros",
        "primary_muscle": "Deltoides",
        "secondary_muscles": '["Tríceps", "Trapecio"]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '[]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 55,
        "instructions_es": '["Sostén las mancuernas frente a la cara con palmas hacia ti", "Empuja hacia arriba rotando las muñecas", "Al llegar arriba las palmas miran hacia adelante", "Baja revirtiendo el movimiento"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Shrugs",
        "name_es": "Encogimientos",
        "description_es": "Ejercicio de aislamiento para el trapecio superior",
        "muscle_group": "Hombros",
        "primary_muscle": "Trapecio superior",
        "secondary_muscles": '[]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '["Barra", "Máquina"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 40,
        "instructions_es": '["De pie con mancuernas a los lados", "Encoge los hombros hacia las orejas lo máximo posible", "Mantén 1 segundo y baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── BRAZOS (Arms) ─────────────────────────────────────────────────────────
    {
        "name": "Barbell Curl",
        "name_es": "Curl con Barra",
        "description_es": "Ejercicio de aislamiento para los bíceps",
        "muscle_group": "Brazos",
        "primary_muscle": "Bíceps",
        "secondary_muscles": '["Braquial", "Braquiorradial"]',
        "equipment_required": '["Barra"]',
        "equipment_alternatives": '["Mancuernas", "Polea baja"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie, agarra la barra con agarre supino", "Flexiona los codos llevando la barra hacia los hombros", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Dumbbell Curl",
        "name_es": "Curl con Mancuerna",
        "description_es": "Curl unilateral con mancuerna para bíceps",
        "muscle_group": "Brazos",
        "primary_muscle": "Bíceps",
        "secondary_muscles": '["Braquial"]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie con una mancuerna en cada mano", "Flexiona los codos alternando brazos", "Rota la muñeca supinando al subir", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Tricep Pushdown",
        "name_es": "Extensión de Tríceps en Polea",
        "description_es": "Ejercicio de aislamiento para los tríceps en polea alta",
        "muscle_group": "Brazos",
        "primary_muscle": "Tríceps",
        "secondary_muscles": '[]',
        "equipment_required": '["Polea alta"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie frente a la polea alta", "Agarra la barra o cuerda con agarre prono", "Extiende los codos llevando las manos hacia abajo", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Bench Tricep Dips",
        "name_es": "Fondos de Tríceps en Banco",
        "description_es": "Fondos de tríceps usando un banco como apoyo",
        "muscle_group": "Brazos",
        "primary_muscle": "Tríceps",
        "secondary_muscles": '["Deltoides anterior"]',
        "equipment_required": '["Banco"]',
        "equipment_alternatives": '["Silla"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 40,
        "instructions_es": '["Apoya las manos en el borde del banco detrás de ti", "Baja el cuerpo flexionando los codos", "Sube extendiendo los codos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Hammer Curl",
        "name_es": "Martillo",
        "description_es": "Curl con agarre neutro para bíceps y braquiorradial",
        "muscle_group": "Brazos",
        "primary_muscle": "Braquiorradial",
        "secondary_muscles": '["Bíceps", "Braquial"]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '["Cuerda en polea"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie con mancuernas en agarre neutro (pulgares arriba)", "Flexiona los codos sin rotar la muñeca", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Skull Crushers",
        "name_es": "Press Francés",
        "description_es": "Extensión de tríceps tumbado con barra o mancuernas",
        "muscle_group": "Brazos",
        "primary_muscle": "Tríceps",
        "secondary_muscles": '[]',
        "equipment_required": '["Barra EZ", "Banco"]',
        "equipment_alternatives": '["Mancuernas"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Recuéstate en el banco con la barra sobre el pecho", "Extiende los brazos y luego flexiona los codos bajando la barra hacia la frente", "Extiende de nuevo los codos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── CORE ──────────────────────────────────────────────────────────────────
    {
        "name": "Plank",
        "name_es": "Plancha",
        "description_es": "Ejercicio isométrico fundamental para el core",
        "muscle_group": "Core",
        "primary_muscle": "Transverso abdominal",
        "secondary_muscles": '["Recto abdominal", "Glúteos", "Hombros"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Apóyate en antebrazos y punteras de los pies", "Mantén el cuerpo recto como una tabla", "Activa el abdomen y glúteos", "Mantén la posición el tiempo indicado"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Crunch",
        "name_es": "Crunch",
        "description_es": "Ejercicio básico para el recto abdominal",
        "muscle_group": "Core",
        "primary_muscle": "Recto abdominal",
        "secondary_muscles": '["Oblicuos"]',
        "equipment_required": '[]',
        "equipment_alternatives": '["Máquina de abdominales"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 40,
        "instructions_es": '["Recuéstate boca arriba con rodillas flexionadas", "Sube el tronco contrayendo el abdomen", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Leg Raise",
        "name_es": "Elevación de Piernas",
        "description_es": "Ejercicio para el abdomen inferior",
        "muscle_group": "Core",
        "primary_muscle": "Recto abdominal inferior",
        "secondary_muscles": '["Flexores de cadera"]',
        "equipment_required": '[]',
        "equipment_alternatives": '["Barra de dominadas"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Recuéstate boca arriba con piernas extendidas", "Eleva las piernas hasta 90 grados manteniendo el abdomen activo", "Baja de forma controlada sin tocar el suelo"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Ab Wheel Rollout",
        "name_es": "Rueda Abdominal",
        "description_es": "Ejercicio avanzado para el core con rueda abdominal",
        "muscle_group": "Core",
        "primary_muscle": "Recto abdominal",
        "secondary_muscles": '["Transverso abdominal", "Dorsal ancho", "Hombros"]',
        "equipment_required": '["Rueda abdominal"]',
        "equipment_alternatives": '["Barra con discos"]',
        "difficulty": "advanced",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Arrodíllate con la rueda frente a ti", "Rueda hacia adelante extendiendo el cuerpo", "Regresa contrayendo el abdomen"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Pallof Press",
        "name_es": "Pallof Press",
        "description_es": "Ejercicio anti-rotación para la estabilidad del core",
        "muscle_group": "Core",
        "primary_muscle": "Oblicuos",
        "secondary_muscles": '["Transverso abdominal"]',
        "equipment_required": '["Polea"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie lateral a la polea", "Sostén el mango frente al pecho", "Empuja hacia adelante resistiendo la rotación", "Regresa de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Bird Dog",
        "name_es": "Bird Dog",
        "description_es": "Ejercicio de estabilidad para el core y la columna",
        "muscle_group": "Core",
        "primary_muscle": "Erector espinal",
        "secondary_muscles": '["Glúteos", "Core"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 50,
        "instructions_es": '["A cuatro patas con espalda recta", "Extiende el brazo derecho y la pierna izquierda simultáneamente", "Mantén 2 segundos y alterna lados"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Dead Bug",
        "name_es": "Dead Bug",
        "description_es": "Ejercicio de core con control anti-extensión lumbar",
        "muscle_group": "Core",
        "primary_muscle": "Transverso abdominal",
        "secondary_muscles": '["Recto abdominal", "Flexores de cadera"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Recuéstate boca arriba con brazos hacia el techo y rodillas a 90 grados", "Baja el brazo derecho y la pierna izquierda simultáneamente", "Regresa y alterna lados manteniendo la espalda pegada al suelo"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── CARDIO / HIIT ─────────────────────────────────────────────────────────
    {
        "name": "Incline Treadmill Walk",
        "name_es": "Caminata Inclinada",
        "description_es": "Cardio de baja intensidad en cinta inclinada",
        "muscle_group": "Cardio",
        "primary_muscle": "Glúteos",
        "secondary_muscles": '["Isquiotibiales", "Gemelos"]',
        "equipment_required": '["Cinta de correr"]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 1800,
        "instructions_es": '["Configura la inclinación al 10-15%", "Camina a ritmo moderado (4-6 km/h)", "Mantén postura erguida sin sujetarte de los pasamanos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Elliptical",
        "name_es": "Elíptica",
        "description_es": "Cardio de bajo impacto en máquina elíptica",
        "muscle_group": "Cardio",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Isquiotibiales", "Pectoral"]',
        "equipment_required": '["Elíptica"]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 1800,
        "instructions_es": '["Sube a la máquina elíptica", "Mantén ritmo constante según el objetivo de frecuencia cardíaca", "Usa también los brazos para mayor gasto calórico"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Rowing Ergometer",
        "name_es": "Remo Ergómetro",
        "description_es": "Cardio de cuerpo completo en máquina de remo",
        "muscle_group": "Cardio",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Piernas", "Core", "Bíceps"]',
        "equipment_required": '["Ergómetro de remo"]',
        "equipment_alternatives": '[]',
        "difficulty": "intermediate",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 1200,
        "instructions_es": '["Siéntate en el ergómetro con los pies sujetos", "Empuja con las piernas, luego jala con los brazos", "Regresa extendiendo brazos y luego flexionando rodillas"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Jump Rope",
        "name_es": "Saltos de Cuerda",
        "description_es": "Cardio de alta intensidad con cuerda de saltar",
        "muscle_group": "Cardio",
        "primary_muscle": "Gemelos",
        "secondary_muscles": '["Hombros", "Core"]',
        "equipment_required": '["Cuerda de saltar"]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 300,
        "instructions_es": '["Sostén los extremos de la cuerda a los lados", "Salta sobre la cuerda manteniendo ritmo constante", "Aterriza suavemente en las puntas de los pies"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Burpees",
        "name_es": "Burpees",
        "description_es": "Ejercicio de cuerpo completo de alta intensidad",
        "muscle_group": "Cardio",
        "primary_muscle": "Cuerpo completo",
        "secondary_muscles": '["Core", "Pecho", "Piernas"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "intermediate",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["De pie, baja las manos al suelo", "Salta los pies hacia atrás en posición de plancha", "Haz una flexión (opcional)", "Salta los pies hacia las manos", "Salta hacia arriba con brazos extendidos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Mountain Climbers",
        "name_es": "Mountain Climbers",
        "description_es": "Ejercicio dinámico de core y cardio",
        "muscle_group": "Cardio",
        "primary_muscle": "Core",
        "secondary_muscles": '["Hombros", "Flexores de cadera"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "cardio",
        "is_unilateral": True,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Posición de plancha con brazos extendidos", "Alterna llevar las rodillas hacia el pecho de forma rápida", "Mantén las caderas bajas"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Box Jumps",
        "name_es": "Box Jumps",
        "description_es": "Saltos sobre cajón pliométrico para potencia y cardio",
        "muscle_group": "Cardio",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Gemelos"]',
        "equipment_required": '["Cajón pliométrico"]',
        "equipment_alternatives": '["Escalón"]',
        "difficulty": "intermediate",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Colócate frente al cajón con pies a la anchura de caderas", "Flexiona rodillas y salta sobre el cajón", "Aterriza suavemente con ambos pies", "Baja dando un paso o saltando"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── MOVILIDAD / FLEXIBILIDAD ──────────────────────────────────────────────
    {
        "name": "Hip Stretch",
        "name_es": "Estiramiento de Cadera",
        "description_es": "Estiramiento estático para flexores y rotadores de cadera",
        "muscle_group": "Movilidad",
        "primary_muscle": "Flexores de cadera",
        "secondary_muscles": '["Glúteos", "Piriforme"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "flexibility",
        "is_unilateral": True,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Arrodíllate en posición de estocada", "Empuja las caderas hacia adelante", "Mantén la posición 30-60 segundos por lado"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Cat-Cow",
        "name_es": "Cat-Cow",
        "description_es": "Movilidad de columna en cuadrupedia",
        "muscle_group": "Movilidad",
        "primary_muscle": "Erector espinal",
        "secondary_muscles": '["Abdomen"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "flexibility",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["A cuatro patas, arquea la espalda hacia arriba (cat)", "Luego baja el abdomen y sube la cabeza (cow)", "Alterna de forma fluida con la respiración"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Thoracic Rotation",
        "name_es": "Rotación Torácica",
        "description_es": "Ejercicio de movilidad para la columna torácica",
        "muscle_group": "Movilidad",
        "primary_muscle": "Columna torácica",
        "secondary_muscles": '["Oblicuos"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "flexibility",
        "is_unilateral": True,
        "estimated_duration_seconds": 60,
        "instructions_es": '["A cuatro patas, pon una mano detrás de la cabeza", "Rota el codo hacia el techo lo máximo posible", "Regresa y repite por el otro lado"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Hip Flexor Stretch",
        "name_es": "Hip Flexor Stretch",
        "description_es": "Estiramiento profundo para el psoas e ilíaco",
        "muscle_group": "Movilidad",
        "primary_muscle": "Psoas",
        "secondary_muscles": '["Ilíaco", "Recto femoral"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "flexibility",
        "is_unilateral": True,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Rodilla trasera en el suelo, pie delantero adelante", "Empuja la cadera hacia adelante y abajo", "Mantén 30-60 segundos por lado"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Pigeon Pose",
        "name_es": "Pigeon Pose",
        "description_es": "Estiramiento profundo de glúteos y rotadores externos de cadera",
        "muscle_group": "Movilidad",
        "primary_muscle": "Glúteo mayor",
        "secondary_muscles": '["Piriforme", "Rotadores externos de cadera"]',
        "equipment_required": '[]',
        "equipment_alternatives": '["Colchoneta"]',
        "difficulty": "intermediate",
        "category": "flexibility",
        "is_unilateral": True,
        "estimated_duration_seconds": 90,
        "instructions_es": '["Desde cuadrupedia, lleva una rodilla hacia la mano del mismo lado", "Extiende la pierna trasera hacia atrás", "Baja el torso hacia el suelo", "Mantén 60-90 segundos por lado"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "World's Greatest Stretch",
        "name_es": "World's Greatest Stretch",
        "description_es": "Estiramiento dinámico multiarticular de cuerpo completo",
        "muscle_group": "Movilidad",
        "primary_muscle": "Cadera",
        "secondary_muscles": '["Columna torácica", "Isquiotibiales", "Flexores de cadera"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "intermediate",
        "category": "flexibility",
        "is_unilateral": True,
        "estimated_duration_seconds": 90,
        "instructions_es": '["Desde zancada, coloca las manos en el suelo dentro del pie delantero", "Rota el torso abriendo el brazo hacia el techo", "Lleva la mano al suelo y extiende la pierna delantera", "Repite la secuencia por el otro lado"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── ESPALDA — additional ──────────────────────────────────────────────────
    {
        "name": "Machine Row",
        "name_es": "Remo Máquina",
        "description_es": "Remo en máquina para la espalda media con apoyo del pecho",
        "muscle_group": "Espalda",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Romboides", "Trapecio medio", "Bíceps"]',
        "equipment_required": '["Máquina de remo"]',
        "equipment_alternatives": '["Polea baja"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Siéntate en la máquina con el pecho apoyado en el pad", "Agarra los mangos con agarre neutro", "Jala hacia el torso apretando los omóplatos", "Regresa de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "T-Bar Row",
        "name_es": "Remo T-Bar",
        "description_es": "Remo con barra T para la espalda media y trapecio",
        "muscle_group": "Espalda",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Romboides", "Bíceps", "Trapecio"]',
        "equipment_required": '["Barra T"]',
        "equipment_alternatives": '["Barra"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 55,
        "instructions_es": '["Colócate sobre la barra T con rodillas ligeramente flexionadas", "Agarra los mangos y jala hacia el abdomen", "Aprieta los omóplatos al final del movimiento", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Straight Arm Pulldown",
        "name_es": "Jalón de Brazos Rectos",
        "description_es": "Aislamiento del dorsal con brazos extendidos en polea alta",
        "muscle_group": "Espalda",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Serrato anterior", "Tríceps largo"]',
        "equipment_required": '["Polea alta"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie frente a la polea alta con brazos extendidos", "Baja el maneral hacia los muslos manteniendo brazos rectos", "Aprieta el dorsal al final", "Regresa de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── CORE — additional ────────────────────────────────────────────────────
    {
        "name": "Russian Twist",
        "name_es": "Russian Twist",
        "description_es": "Ejercicio de rotación para los oblicuos",
        "muscle_group": "Core",
        "primary_muscle": "Oblicuos",
        "secondary_muscles": '["Recto abdominal"]',
        "equipment_required": '[]',
        "equipment_alternatives": '["Disco", "Balón medicinal"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Siéntate con rodillas flexionadas y tronco inclinado 45 grados", "Junta las manos frente al pecho", "Rota el tronco de lado a lado de forma controlada", "Mantén el abdomen activo durante todo el movimiento"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Hollow Body Hold",
        "name_es": "Hollow Body Hold",
        "description_es": "Posición isométrica de core con columna en flexión",
        "muscle_group": "Core",
        "primary_muscle": "Recto abdominal",
        "secondary_muscles": '["Transverso abdominal", "Flexores de cadera"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 30,
        "instructions_es": '["Recuéstate boca arriba y extiende brazos sobre la cabeza", "Eleva hombros y piernas del suelo a la vez", "Aplana la zona lumbar contra el suelo", "Mantén la posición el tiempo indicado"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Side Plank",
        "name_es": "Plancha Lateral",
        "description_es": "Variante lateral de la plancha para oblicuos y estabilidad",
        "muscle_group": "Core",
        "primary_muscle": "Oblicuos",
        "secondary_muscles": '["Glúteo medio", "Transverso abdominal"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 30,
        "instructions_es": '["Apóyate en el antebrazo lateral y en el borde del pie", "Mantén el cuerpo recto de cabeza a pies", "Activa el core y glúteo", "Repite por el otro lado"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── CARDIO — additional ──────────────────────────────────────────────────
    {
        "name": "Sprints",
        "name_es": "Sprints",
        "description_es": "Carreras de alta intensidad a máxima velocidad",
        "muscle_group": "Cardio",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Isquiotibiales", "Glúteos", "Gemelos"]',
        "equipment_required": '[]',
        "equipment_alternatives": '["Cinta de correr"]',
        "difficulty": "advanced",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 30,
        "instructions_es": '["Calienta 5 minutos caminando o trotando", "Corre a máxima velocidad durante 20-30 segundos", "Camina o trota 90 segundos de recuperación", "Repite según el protocolo de entrenamiento"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Cycling",
        "name_es": "Ciclismo / Bicicleta Estática",
        "description_es": "Cardio de bajo impacto en bicicleta estática o de montaña",
        "muscle_group": "Cardio",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Isquiotibiales", "Gemelos"]',
        "equipment_required": '["Bicicleta estática"]',
        "equipment_alternatives": '["Bicicleta de montaña"]',
        "difficulty": "beginner",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 1800,
        "instructions_es": '["Ajusta el asiento a la altura correcta", "Pedalea a ritmo constante según el objetivo de frecuencia cardíaca", "Mantén la postura erguida"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Stair Climber",
        "name_es": "Escaladora",
        "description_es": "Cardio de alta demanda para piernas en máquina escaladora",
        "muscle_group": "Cardio",
        "primary_muscle": "Glúteos",
        "secondary_muscles": '["Cuádriceps", "Isquiotibiales", "Gemelos"]',
        "equipment_required": '["Escaladora"]',
        "equipment_alternatives": '["Escaleras"]',
        "difficulty": "intermediate",
        "category": "cardio",
        "is_unilateral": False,
        "estimated_duration_seconds": 1200,
        "instructions_es": '["Súbete a la máquina escaladora", "Mantén ritmo moderado-alto", "No te apoyes demasiado en los pasamanos", "Mantén postura erguida"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── MOVILIDAD — additional ───────────────────────────────────────────────
    {
        "name": "Foam Roller IT Band",
        "name_es": "Foam Roller",
        "description_es": "Auto-masaje con rodillo para liberación miofascial",
        "muscle_group": "Movilidad",
        "primary_muscle": "Fascia lata / banda IT",
        "secondary_muscles": '["Cuádriceps", "Isquiotibiales", "Gemelos"]',
        "equipment_required": '["Foam roller"]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "flexibility",
        "is_unilateral": True,
        "estimated_duration_seconds": 120,
        "instructions_es": '["Coloca el foam roller bajo el músculo objetivo", "Aplica presión corporal y rueda lentamente", "Pausa en puntos de tensión 5-10 segundos", "Repite en ambos lados"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Ankle Circles",
        "name_es": "Círculos de Tobillo",
        "description_es": "Movilidad articular para el tobillo",
        "muscle_group": "Movilidad",
        "primary_muscle": "Tobillo",
        "secondary_muscles": '["Gemelos", "Tibial anterior"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "flexibility",
        "is_unilateral": True,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Siéntate o párate en un pie", "Realiza círculos lentos con el tobillo en ambas direcciones", "10 repeticiones por dirección y por tobillo"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Shoulder Circles",
        "name_es": "Círculos de Hombro",
        "description_es": "Movilidad articular dinámica para el hombro",
        "muscle_group": "Movilidad",
        "primary_muscle": "Manguito rotador",
        "secondary_muscles": '["Deltoides", "Trapecio"]',
        "equipment_required": '[]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "flexibility",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["De pie con brazos a los lados", "Realiza círculos amplios hacia adelante con ambos hombros", "Luego repite hacia atrás"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── PECHO — additional ───────────────────────────────────────────────────
    {
        "name": "Decline Bench Press",
        "name_es": "Press Banca Declinado",
        "description_es": "Variante declinada del press de banca para la porción inferior del pecho",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor (porción esternocostal)",
        "secondary_muscles": '["Tríceps", "Deltoides anterior"]',
        "equipment_required": '["Barra", "Banco declinado"]',
        "equipment_alternatives": '["Mancuernas"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Recuéstate en el banco declinado con pies sujetos", "Agarra la barra a la anchura de hombros", "Baja la barra hasta la parte inferior del pecho", "Empuja hasta extender los brazos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Pec Deck",
        "name_es": "Pec Deck / Mariposa Máquina",
        "description_es": "Aislamiento del pectoral en máquina mariposa",
        "muscle_group": "Pecho",
        "primary_muscle": "Pectoral mayor",
        "secondary_muscles": '["Deltoides anterior"]',
        "equipment_required": '["Máquina mariposa"]',
        "equipment_alternatives": '["Poleas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Siéntate en la máquina con los codos a la altura de los hombros", "Cierra los brazos hacia el centro apretando el pecho", "Regresa de forma controlada sin perder la tensión"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── PIERNAS — additional ─────────────────────────────────────────────────
    {
        "name": "Romanian Deadlift",
        "name_es": "Peso Muerto Rumano",
        "description_es": "Variante del peso muerto con énfasis en isquiotibiales",
        "muscle_group": "Piernas",
        "primary_muscle": "Isquiotibiales",
        "secondary_muscles": '["Glúteos", "Erector espinal"]',
        "equipment_required": '["Barra"]',
        "equipment_alternatives": '["Mancuernas"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 60,
        "instructions_es": '["De pie con la barra frente a los muslos", "Inclínate hacia adelante con espalda recta y rodillas ligeramente flexionadas", "Baja la barra hasta sentir el estiramiento en los isquiotibiales", "Vuelve a la posición inicial contrayendo los glúteos"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Bulgarian Split Squat",
        "name_es": "Sentadilla Búlgara",
        "description_es": "Sentadilla unilateral con pie trasero elevado",
        "muscle_group": "Piernas",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Isquiotibiales"]',
        "equipment_required": '["Banco"]',
        "equipment_alternatives": '["Silla", "Step"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 60,
        "instructions_es": '["Coloca el pie trasero sobre el banco", "Baja la rodilla trasera hacia el suelo", "Mantén el tronco erguido", "Sube empujando con la pierna delantera"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Sumo Squat",
        "name_es": "Sentadilla Sumo",
        "description_es": "Sentadilla con piernas abiertas para mayor activación de aductores",
        "muscle_group": "Piernas",
        "primary_muscle": "Aductores",
        "secondary_muscles": '["Cuádriceps", "Glúteos"]',
        "equipment_required": '[]',
        "equipment_alternatives": '["Mancuerna", "Kettlebell"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Pies más abiertos que los hombros con puntas hacia afuera", "Baja en sentadilla manteniendo el tronco erguido", "Empuja desde los talones al subir"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── HOMBROS — additional ─────────────────────────────────────────────────
    {
        "name": "Cable Lateral Raise",
        "name_es": "Elevación Lateral en Polea",
        "description_es": "Elevación lateral unilateral con polea baja",
        "muscle_group": "Hombros",
        "primary_muscle": "Deltoides lateral",
        "secondary_muscles": '["Trapecio superior"]',
        "equipment_required": '["Polea baja"]',
        "equipment_alternatives": '["Mancuernas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie lateral a la polea baja", "Agarra el maneral con la mano alejada de la máquina", "Eleva el brazo lateralmente hasta la altura del hombro", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Upright Row",
        "name_es": "Remo al Mentón",
        "description_es": "Ejercicio compuesto para trapecios y deltoides",
        "muscle_group": "Hombros",
        "primary_muscle": "Trapecio superior",
        "secondary_muscles": '["Deltoides lateral", "Bíceps"]',
        "equipment_required": '["Barra"]',
        "equipment_alternatives": '["Mancuernas", "Polea baja"]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie con la barra a agarre prono estrecho", "Eleva la barra hacia el mentón con codos apuntando hacia arriba", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── BRAZOS — additional ──────────────────────────────────────────────────
    {
        "name": "Concentration Curl",
        "name_es": "Curl Concentrado",
        "description_es": "Curl de bíceps con codo apoyado en la pierna para máximo aislamiento",
        "muscle_group": "Brazos",
        "primary_muscle": "Bíceps",
        "secondary_muscles": '["Braquial"]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Sentado con el codo apoyado en la cara interna del muslo", "Flexiona el codo llevando la mancuerna al hombro", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Overhead Tricep Extension",
        "name_es": "Extensión de Tríceps sobre la Cabeza",
        "description_es": "Extensión de tríceps con mancuerna sobre la cabeza",
        "muscle_group": "Brazos",
        "primary_muscle": "Tríceps",
        "secondary_muscles": '[]',
        "equipment_required": '["Mancuernas"]',
        "equipment_alternatives": '["Polea alta", "Barra EZ"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Sostén una mancuerna sobre la cabeza con ambas manos", "Flexiona los codos bajando la mancuerna detrás de la cabeza", "Extiende los codos para regresar a la posición inicial"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Cable Curl",
        "name_es": "Curl en Polea",
        "description_es": "Curl de bíceps en polea baja con tensión constante",
        "muscle_group": "Brazos",
        "primary_muscle": "Bíceps",
        "secondary_muscles": '["Braquiorradial"]',
        "equipment_required": '["Polea baja"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["De pie frente a la polea baja", "Agarra el maneral con agarre supino", "Flexiona los codos llevando las manos a los hombros", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── ESPALDA — additional 2 ───────────────────────────────────────────────
    {
        "name": "Hyperextension",
        "name_es": "Hiperextensión de Espalda",
        "description_es": "Ejercicio para el erector espinal y glúteos en banco de hiperextensión",
        "muscle_group": "Espalda",
        "primary_muscle": "Erector espinal",
        "secondary_muscles": '["Glúteos", "Isquiotibiales"]',
        "equipment_required": '["Banco de hiperextensión"]',
        "equipment_alternatives": '[]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Coloca las caderas sobre el pad del banco de hiperextensión", "Baja el tronco de forma controlada", "Sube hasta la posición neutral sin hiperextender la espalda"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Meadows Row",
        "name_es": "Remo Meadows",
        "description_es": "Remo unilateral con barra en el suelo para la espalda",
        "muscle_group": "Espalda",
        "primary_muscle": "Dorsal ancho",
        "secondary_muscles": '["Romboides", "Bíceps", "Core"]',
        "equipment_required": '["Barra"]',
        "equipment_alternatives": '[]',
        "difficulty": "intermediate",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 55,
        "instructions_es": '["Coloca un extremo de la barra en un rincón", "De pie lateral a la barra, agarra el extremo con una mano", "Jala hacia la cadera del mismo lado apretando el dorsal", "Baja de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    # ── PIERNAS — additional 2 ───────────────────────────────────────────────
    {
        "name": "Abductor Machine",
        "name_es": "Máquina Abductora",
        "description_es": "Ejercicio de aislamiento para el glúteo medio y abductores",
        "muscle_group": "Piernas",
        "primary_muscle": "Glúteo medio",
        "secondary_muscles": '["Tensor de la fascia lata"]',
        "equipment_required": '["Máquina abductora"]',
        "equipment_alternatives": '["Bandas elásticas"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": False,
        "estimated_duration_seconds": 45,
        "instructions_es": '["Siéntate en la máquina con las rodillas contra los pads", "Abre las piernas contra la resistencia", "Regresa de forma controlada"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
    {
        "name": "Step Up",
        "name_es": "Subida al Banco",
        "description_es": "Ejercicio funcional unilateral para piernas y glúteos",
        "muscle_group": "Piernas",
        "primary_muscle": "Cuádriceps",
        "secondary_muscles": '["Glúteos", "Isquiotibiales"]',
        "equipment_required": '["Banco"]',
        "equipment_alternatives": '["Step", "Escalón"]',
        "difficulty": "beginner",
        "category": "strength",
        "is_unilateral": True,
        "estimated_duration_seconds": 50,
        "instructions_es": '["Colócate frente al banco", "Sube con un pie y empuja para subir completamente", "Baja el pie de vuelta al suelo de forma controlada", "Alterna piernas"]',
        "image_urls": "[]",
        "thumbnail_url": None,
        "video_url": None,
    },
]


def seed() -> None:
    db = SessionLocal()
    try:
        repo = ExerciseRepository(db)
        for ex in EXERCISES:
            repo.upsert(ex)
        db.commit()
        print(f"Seeded {len(EXERCISES)} exercises successfully.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
